info:
    description: "HandlessFoo REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "HandlessFoo"
    version: v1.0
openapi: 3.0.1
components:
  schemas:
    Foo:
      description: Contains all of the data for a single foo.
      properties:
        name:
          description: Foo name.
          type: string
        id:
          description: The foo internal ID.
          type: string
        groupId:
          description: Group ID.
          type: string
      type: object
paths:
  "/foos":
    get:
      operationId: getFoosPage
      tags: ["Foo"]
      description: Retrieves the list of foos. Results can be paginated, filtered, searched, and sorted.
      parameters:
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: search
          schema:
            type: string
        - in: query
          name: sort
          schema:
            type: string
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Foo"
                type: array
            application/xml:
              schema:
                items:
                  $ref: "#/components/schemas/Foo"
                type: array
    post:
      operationId: postFoo
      tags: ["Foo"]
      description: Create a new item.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Foo"
          application/xml:
            schema:
              $ref: "#/components/schemas/Foo"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Foo"
            application/xml:
              schema:
                $ref: "#/components/schemas/Foo"
  "/foos/{fooId}":
    get:
      operationId: getFoo
      tags: ["Foo"]
      description: Retrieves the item via its ID.
      parameters:
        - name: fooId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Foo"
            application/xml:
              schema:
                $ref: "#/components/schemas/Foo"
